services:
  db:
    container_name: postgresql
    image: sameersbn/postgresql:12-20200524
    environment:
      PG_PASSWORD: $DB_PASS
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
      DB_HOST: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
    networks:
      - appnetwork
    volumes:
      - ./postgres-data:/var/lib/postgresql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - appnetwork


  app:
    container_name: app
    build:
      context: .
    command: uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    restart: always
    networks:
      - appnetwork
    env_file:
      - ".env"
    volumes:
      - ./backend:/app
    depends_on:
      - db

networks:
  appnetwork:
    driver: bridge