version: '3.8'

services:
  sync_service:
    build: .
    environment:
      - PG_HOST=${PG_HOST}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_VIEW=${PG_VIEW}
      - WORKSHEET_NAME=${WORKSHEET_NAME}
      - SHEET_NAME=${SHEET_NAME}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
    restart: always
    volumes:
      - ./app/creds.json:/app/creds.json