# Базовый Python образ
FROM python:3.11-slim

# Установка зависимостей
WORKDIR /app

# Копируем папку telegram_bot
COPY telegram_bot/ /app/

# Устанавливаем зависимости
COPY telegram_bot/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Запуск Telegram-бота
CMD ["python", "bot.py"]